# Numpy

In [1]:
import numpy as np

## 1. datatype & Attributes

In [2]:
# NumPy's main data type ia ndarray
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [3]:
# ndarray = n dimensional array
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4.2, 5, 6.1]])

a3 = np.array([[[1.5, 2, 3.5],
                [4.2, 5, 6.4],
                [7, 8.1, 9.0]],
               [[10, 11, 12.0],
                [13, 14, 15.0],
                [16, 17.0, 18]]])

In [5]:
a1

array([1, 2, 3, 4, 5])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4.2, 5. , 6.1]])

In [7]:
a3

array([[[ 1.5,  2. ,  3.5],
        [ 4.2,  5. ,  6.4],
        [ 7. ,  8.1,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
#Checking the data types of elements in the arrays
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('float64'))

In [10]:
# checking the size of an array 
a1.size, a2.size, a3.size

(5, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
#Creating dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.2  5.0  6.1

## 2. creating array

In [14]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [17]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 1, 3, 0, 6],
       [7, 8, 1, 7, 9],
       [8, 3, 2, 0, 1]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.59360685, 0.59411314, 0.67459506],
       [0.95013688, 0.90260521, 0.00503869],
       [0.63458083, 0.70241153, 0.11565064],
       [0.17893432, 0.90682533, 0.00256415],
       [0.09204476, 0.75899568, 0.64016708]])

In [25]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.95559246, 0.06155322, 0.96267348],
       [0.20532669, 0.64231448, 0.50768431],
       [0.58825386, 0.85569357, 0.04755025],
       [0.57932601, 0.35299053, 0.85797203],
       [0.839986  , 0.08129179, 0.73010265]])

In [30]:
#Pseudo random number
np.random.seed( seed = 0)
random_array_4 = np.random.randint(10, size = (5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [31]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1

array([1, 2, 3, 4, 5])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4.2, 5. , 6.1]])

In [34]:
a3

array([[[ 1.5,  2. ,  3.5],
        [ 4.2,  5. ,  6.4],
        [ 7. ,  8.1,  9. ]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [35]:
a3[0]

array([[1.5, 2. , 3.5],
       [4.2, 5. , 6.4],
       [7. , 8.1, 9. ]])

In [39]:
a3[1][1][0]

13.0

In [42]:
a3[:0, :0, :1]

array([], shape=(0, 0, 1), dtype=float64)